language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get install portaudio19-dev

install:
  - pip install git+http://people.csail.mit.edu/hubert/git/pyaudio.git
  - pip install .
  - pip install coveralls pep8 mock

script:
  - pep8 amodem/ scripts/ tests/ amodem-cli
  - cd tests
  - coverage run --source=amodem -m py.test
