sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install coveralls pep8 mock pylint

script:
  - pep8 amodem/ scripts/ tests/ amodem-cli
  - pylint --extension-pkg-whitelist=numpy --report=no amodem
  - cd tests
  - coverage run --source=amodem -m py.test

after_success:
  - coveralls
