sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install coveralls pep8 mock

script:
  - pep8 amodem/ scripts/
  - echo "Hello World!" | amodem send -vv -l- -o- | amodem recv -vv -l- -i-
  - coverage run --source=amodem --omit="*/__main__.py" -m py.test -vvs

after_success:
  - coverage report
  - coveralls
